- name: mysql.cnfの配置
  become: yes
  template:
    src=.my.cnf.template
    dest={{ my_cnf_path }}
    owner=root
    group=root
    mode=0600

- name: MySQLの再起動
  become: yes
  service:
    name=mysqld
    state=restarted
    enabled=yes

- name: MySQL データベース作成
  become: yes
  mysql_db:
    name=redmine
    encoding=utf8
    login_host=localhost
    login_password={{ db_passwd_redmine }}
    login_user=root
