- name: mysql.cnfの配置
  become: yes
  template:
    src=.my.cnf.template
    dest={{ my_cnf_path }}
    owner: root
    group: root
    mode: 0600

- name: MySQLの再起動
  become: yes
  service:
    name=mysqld
    state=restarted
    enabled=yes

- name: root ユーザのパスワード変更
  mysql_user:
    name=root
    host={{ item }}
    password={{ db_passwd_redmine }}
  with_items:
    - localhost

- name: MySQLユーザー作成
  become: yes
  become_user: mysql
  become_method: su
  mysql_user:
    name=mysql
    password={{ db_passwd_redmine }}

- name: MySQL データベース作成
  become: yes
  become_user: mysql
  become_method: su
  mysql_db:
    name=redmine
    encoding='UTF-8'
    lc_collate='ja_JP.UTF-8'
    lc_ctype='ja_JP.UTF-8'
    template='template0'
