- name: mysql.cnfの配置
  become: yes
  copy:
    src=my.cnf
    dest={{ work_dir }}

- name: MySQLの初期設定
  become: yes
  service:
    name=mysqld
    state=start
    enabled=yes

- name: セキュリティ設定
  become: yes
  shell:
    mysql_secure_installation

- name: MySQLユーザー作成
  become: yes
  become_user: admin
  become_method: su
  mysql_user:
    name=admin
    password={{ db_passwd_redmine }}

- name: MySQL データベース作成
  become: yes
  become_user: admin
  become_method: su
  mysql_db:
    name=redmine
    encoding='UTF-8'
    lc_collate='ja_JP.UTF-8'
    lc_ctype='ja_JP.UTF-8'
    template='template0'
