- name: anonymous ユーザの削除
  mysql_user:
    name: ""
    host: "{{ item }}"
    state: absent
  with_items:
    - localhost.localdomain
    - localhost
  when: init_flag.rc == 1

- name: root ユーザのパスワード変更
  mysql_user:
    name: "root"
    host: "{{ item }}"
    password: "{{ db_passwd_redmine }}"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost.localdomain
    - localhost
    - keis-redmine.prod.local
  when: init_flag.rc == 1

- name: mysql.cnfの配置
  become: yes
  copy:
    src=my.cnf
    dest={{ work_dir }}

- name: MySQLの初期設定
  become: yes
  service:
    name=mysqld
    state=start
    enabled=yes

- name: セキュリティ設定
  become: yes
  shell:
    mysql_secure_installation

- name: MySQLユーザー作成
  become: yes
  become_user: admin
  become_method: su
  mysql_user:
    name=admin
    password={{ db_passwd_redmine }}

- name: MySQL データベース作成
  become: yes
  become_user: admin
  become_method: su
  mysql_db:
    name=redmine
    encoding='UTF-8'
    lc_collate='ja_JP.UTF-8'
    lc_ctype='ja_JP.UTF-8'
    template='template0'
